# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - 7
  ldflags:
    - -s -w -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .ShortCommit }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - none*
checksum:
  name_template: 'checksums_{{ .ShortCommit }}.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  name_template: "{{.Version}}-v{{.ShortCommit}}"
